### ISSUE TITLE
Unable to run the flutter example on windows

### ISSUE THREAD

**Issue by 0Vipin0** [harmonoid/libwinmedia#11]
Steps to reproduce:
1. Simply run the flutter example on windows

Issue:
I am not able to run the example on Windows.

Flutter Run Logs:
[ +144 ms] executing: [C:\Users\Vipin Malik\fvm\versions\stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1045 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +7 ms] executing: [C:\Users\Vipin Malik\fvm\versions\stable/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[ +148 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +9 ms] 2.2.3
[  +10 ms] executing: [C:\Users\Vipin Malik\fvm\versions\stable/] git rev-parse --abbrev-ref --symbolic @{u}
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +6 ms] executing: [C:\Users\Vipin Malik\fvm\versions\stable/] git ls-remote --get-url origin
[  +48 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +205 ms] executing: [C:\Users\Vipin Malik\fvm\versions\stable/] git rev-parse --abbrev-ref HEAD
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +120 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +88 ms] executing: C:\Users\Vipin Malik\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +38 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +116 ms] executing: C:\Users\Vipin Malik\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +33 ms] Skipping pub get: version match.
[  +80 ms] Found plugin libwinmedia at F:\Open-Source\libwinmedia\flutter\
[ +643 ms] Found plugin libwinmedia at F:\Open-Source\libwinmedia\flutter\
[ +170 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations
[   +7 ms] complete
[   +8 ms] Launching lib\main.dart on Windows in debug mode...
[  +10 ms] C:\Users\Vipin Malik\fvm\versions\stable\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\Vipin
Malik\fvm\versions\stable\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\Vipin Malik\fvm\versions\stable\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\VIPINM~1\AppData\Local\Temp\flutter_tools.5c57fce5\flutter_tool.ca55c4ca\app.dill --packages F:\Open-Source\libwinmedia\flutter\example\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +60 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +44 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +3 ms] [
             {
               "instanceId": "a458a554",
               "installDate": "2020-09-23T17:57:52Z",
               "installationName": "VisualStudio/16.7.4+30517.126",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.7.30517.126",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.7.4",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2020-09-23T17:57:51.9916061Z",
               "catalog": {
                 "buildBranch": "d16.7",
                 "buildVersion": "16.7.30517.126",
                 "id": "VisualStudio/16.7.4+30517.126",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.7.4",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "4",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.7.4+30517.126",
                 "requiredEngineVersion": "2.7.3132.26759"
               },
               "properties": {
                 "campaignId": "",
                 "canceled": "0",
                 "channelManifestId": "VisualStudio.16.Release/16.7.4+30517.126",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[   +9 ms] Building Windows application...
[  +37 ms] <- compile package:libwinmedia_example/main.dart
[  +26 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S F:\Open-Source\libwinmedia\flutter\example\windows -B
build\windows -G Visual Studio 16 2019
[  +31 ms] List of devices attached
[   +9 ms] List of devices attached
[+1156 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
[  +63 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/libwinmedia/windows/CMakeLists.txt:7 (add_subdirectory):
[   +7 ms]   add_subdirectory given source
[   +6 ms]   "F:/Open-Source/libwinmedia/flutter/example/windows/flutter/ephemeral/.plugin_symlinks/libwinmedia/windows/../.master"
[   +1 ms]   which is not an existing directory.
[   +1 ms] -- Configuring incomplete, errors occurred!
[   +1 ms] See also "F:/Open-Source/libwinmedia/flutter/example/build/windows/CMakeFiles/CMakeOutput.log".
[  +32 ms] Building Windows application... (completed in 1,352ms)
[+13400 ms] Exception: Unable to generate build files
[   +3 ms] "flutter run" took 16,201ms.
[  +16 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[ +269 ms] ensureAnalyticsSent: 264ms
[   +5 ms] Running shutdown hooks
[   +5 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

Flutter Doctor Logs:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] VS Code (version 1.59.1)
[√] Connected device (3 available)

• No issues found!

**Comment by alexmercerind** [comment]
@0Vipin0 did you clone the repository?

**Comment by alexmercerind** [comment]
If yes, you need to fetch respective submodules aswell. 

```
git submodule update --init --recursive
```

Learn more: https://stackoverflow.com/a/8084186/12825435

**Comment by 0Vipin0** [comment]
Tried that also but issue is still coming.

Steps taken:
`git submodule update --init --recursive`

`git pull --recurse-submodules --jobs=10`

`flutter clean`

`flutter run -d windows`

Flutter Run Logs: 
Running "flutter pub get" in example...
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
CMake Error at flutter/ephemeral/.plugin_symlinks/libwinmedia/windows/CMakeLists.txt:7 (add_subdirectory):
  add_subdirectory given source
  "F:/Open-Source/libwinmedia/flutter/example/windows/flutter/ephemeral/.plugin_symlinks/libwinmedia/windows/../.master"
  which is not an existing directory.


Exception: Unable to generate build files

**Comment by bdlukaa** [comment]
You can clone again with `--recursive`

**Comment by alexmercerind** [comment]
Let know if it doesn't work. Not issue with library regardless. It could be issue that your `git` CLI isn't updated & symlinks aren't getting generated correctly.

**Comment by 0Vipin0** [comment]
After cloning from again with recursive flag, it still doesn't work.

`git clone --recursive https://github.com/harmonoid/libwinmedia.git`

`flutter clean`

Same error before is coming

**Comment by alexmercerind** [comment]
@0Vipin0 could you send screenshot of the `flutter` folder ? (inside the folder that you cloned)

**Comment by 0Vipin0** [comment]
Here is my folder structure of the flutter folder inside the cloned repo.

![image](https://user-images.githubusercontent.com/40391904/136231229-3312e444-5609-4857-bab7-5b99a959429b.png)

**Comment by 0Vipin0** [comment]
@alexmercerind  I have updated the git to the latest version for windows, cloned the repo again and ran the example again but the issue still persist.

**Comment by alexmercerind** [comment]
@0Vipin0,
See how my git has generated automatic shortcut based on Linux type symlink (unlike yours).

![Screenshot 2021-10-06 230249](https://user-images.githubusercontent.com/28951144/136264255-b8f03687-1b3d-42bf-a659-9aef2ee6b56b.png)

@bdlukaa 

back then, I didn't know much about submodules. Using `file()` from CMake, it can cause problems for developers in country where GitHub available. Extracting contents of archive adds another process to the game. Didn't wanna go with it.

**Comment by yhsj0919** [comment]
![image](https://user-images.githubusercontent.com/7219412/141064758-f28fad50-c69f-4803-85d5-c9ad4c7c55bb.png)
But it can run on 16.11.3

**Comment by lc-os** [comment]
![142393842-860d57f8-2ce2-4b42-a842-a5e478c42fc4](https://user-images.githubusercontent.com/17776446/142830512-1fc0c137-4704-41b4-b36c-e18af0bc5ece.png)
Download and replace this file through the URL
