### ISSUE TITLE
Report errors

### ISSUE THREAD

**Issue by bdlukaa** [harmonoid/libwinmedia#5]
Can be done through [this event handler](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.mediafailed?view=winrt-20348) on windows and

```html
    _audioElement.addEventListener('error', (event) {
      _durationCompleter?.completeError(_audioElement.error!);
    });
```

on linux.

**Comment by alexmercerind** [comment]
Done. But, `MediaFailed` doesn't seem to ever get invoked on Windows.
